/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: "jit",
  safelist: [
    // Some dynamic class names
    // "text-orange-500",
    // "text-red-500",
    // "text-amber-500",
    // "text-green-500",
    // "border-orange-500",
    // "border-red-500",
    // "border-amber-500",
    // "border-green-500",
    // "bg-orange-200",
    // "bg-red-200",
    // "bg-amber-200",
    // "bg-green-200",
    "bg-[#78716c]",
    "bg-[#3b82f6]",
    "bg-[#ec4899]",
    "bg-[#10b981]",
    "bg-[#f97316]",
    "bg-[#0ea5e9]",
    "bg-[#10b981]",
    { pattern: /(bg|text|border)-./ },
    { pattern: /^\-?m(\w?)-/ },
  ],
  important: true,
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    screens: {
      sm: '480px',
      md: '768px',
      lg: '976px',
      xl: '1440px',
    },
    extend: {},
  },
  plugins: [],
};
